name: Release application

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.8"
      - run: go test -v -cover -parallel 2 ./trss...
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.8"
      - run: go build -o ./bin/trss ./main.go
  push:
    runs-on: ubuntu-20.04
    needs:
      - test
      - build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t iben12/transmission-rss-go:latest -t iben12/transmission-rss-go:${{ env.GIT_TAG_NAME }} .
      - name: Push to DockerHub
        run: docker push --all-tags iben12/transmission-rss-go
